name: bench
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.3
        working-directory: ssg/jekyll

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Setup Deno
      uses: denoland/setup-deno@v1

    - name: Install eleventy
      run: |
        cd ssg/eleventy
        npm install

    - name: Install lume
      run: |
        deno install --allow-run --allow-env --allow-read --name lume --force --reload --global https://deno.land/x/lume_cli/mod.ts

    - name: Run the benchmarks
      run: |
        deno run --unstable -A cli.js --pages 1
        deno run --unstable -A cli.js --pages 10
        deno run --unstable -A cli.js --pages 100
        deno run --unstable -A cli.js --pages 1000
        deno run --unstable -A cli.js --pages 10000
